// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: filespb/messages.proto

package filespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_filespb_messages_proto protoreflect.FileDescriptor

var file_filespb_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x31, 0x42, 0x0d, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65,
	0x73, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x70, 0x62,
}

var file_filespb_messages_proto_goTypes = []interface{}{}
var file_filespb_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filespb_messages_proto_init() }
func file_filespb_messages_proto_init() {
	if File_filespb_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filespb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filespb_messages_proto_goTypes,
		DependencyIndexes: file_filespb_messages_proto_depIdxs,
	}.Build()
	File_filespb_messages_proto = out.File
	file_filespb_messages_proto_rawDesc = nil
	file_filespb_messages_proto_goTypes = nil
	file_filespb_messages_proto_depIdxs = nil
}
