// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: gatespb/api.proto

package gatespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FilesRequest) Reset() {
	*x = FilesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesRequest) ProtoMessage() {}

func (x *FilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesRequest.ProtoReflect.Descriptor instead.
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{0}
}

func (x *FilesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FilesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FilesResponse) Reset() {
	*x = FilesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesResponse) ProtoMessage() {}

func (x *FilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesResponse.ProtoReflect.Descriptor instead.
func (*FilesResponse) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{1}
}

func (x *FilesResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FromBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TranscodeBodyBucket *TranscodeBodyBucket `protobuf:"bytes,1,opt,name=transcode_body_bucket,json=transcodeBodyBucket,proto3" json:"transcode_body_bucket,omitempty"`
}

func (x *FromBucketRequest) Reset() {
	*x = FromBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromBucketRequest) ProtoMessage() {}

func (x *FromBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromBucketRequest.ProtoReflect.Descriptor instead.
func (*FromBucketRequest) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{2}
}

func (x *FromBucketRequest) GetTranscodeBodyBucket() *TranscodeBodyBucket {
	if x != nil {
		return x.TranscodeBodyBucket
	}
	return nil
}

type FromBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FromBucketResponse) Reset() {
	*x = FromBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FromBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromBucketResponse) ProtoMessage() {}

func (x *FromBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromBucketResponse.ProtoReflect.Descriptor instead.
func (*FromBucketResponse) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{3}
}

func (x *FromBucketResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TranscodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TranscodeBody *TranscodeBody `protobuf:"bytes,1,opt,name=transcode_body,json=transcodeBody,proto3" json:"transcode_body,omitempty"`
}

func (x *TranscodeRequest) Reset() {
	*x = TranscodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequest) ProtoMessage() {}

func (x *TranscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequest.ProtoReflect.Descriptor instead.
func (*TranscodeRequest) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{4}
}

func (x *TranscodeRequest) GetTranscodeBody() *TranscodeBody {
	if x != nil {
		return x.TranscodeBody
	}
	return nil
}

type TranscodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TranscodeResponse) Reset() {
	*x = TranscodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeResponse) ProtoMessage() {}

func (x *TranscodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeResponse.ProtoReflect.Descriptor instead.
func (*TranscodeResponse) Descriptor() ([]byte, []int) {
	return file_gatespb_api_proto_rawDescGZIP(), []int{5}
}

func (x *TranscodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_gatespb_api_proto protoreflect.FileDescriptor

var file_gatespb_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x1a, 0x16, 0x67, 0x61,
	0x74, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x65, 0x0a,
	0x11, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x50, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x5f, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x51, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x2b, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0xd7, 0x01, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70,
	0x62, 0x2e, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x73, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x42, 0x08, 0x41, 0x70, 0x69,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2f,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x07,
	0x47, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0xca, 0x02, 0x07, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70,
	0x62, 0xe2, 0x02, 0x13, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gatespb_api_proto_rawDescOnce sync.Once
	file_gatespb_api_proto_rawDescData = file_gatespb_api_proto_rawDesc
)

func file_gatespb_api_proto_rawDescGZIP() []byte {
	file_gatespb_api_proto_rawDescOnce.Do(func() {
		file_gatespb_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_gatespb_api_proto_rawDescData)
	})
	return file_gatespb_api_proto_rawDescData
}

var file_gatespb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gatespb_api_proto_goTypes = []interface{}{
	(*FilesRequest)(nil),        // 0: gatespb.FilesRequest
	(*FilesResponse)(nil),       // 1: gatespb.FilesResponse
	(*FromBucketRequest)(nil),   // 2: gatespb.FromBucketRequest
	(*FromBucketResponse)(nil),  // 3: gatespb.FromBucketResponse
	(*TranscodeRequest)(nil),    // 4: gatespb.TranscodeRequest
	(*TranscodeResponse)(nil),   // 5: gatespb.TranscodeResponse
	(*TranscodeBodyBucket)(nil), // 6: gatespb.TranscodeBodyBucket
	(*TranscodeBody)(nil),       // 7: gatespb.TranscodeBody
}
var file_gatespb_api_proto_depIdxs = []int32{
	6, // 0: gatespb.FromBucketRequest.transcode_body_bucket:type_name -> gatespb.TranscodeBodyBucket
	7, // 1: gatespb.TranscodeRequest.transcode_body:type_name -> gatespb.TranscodeBody
	0, // 2: gatespb.GatesService.Files:input_type -> gatespb.FilesRequest
	2, // 3: gatespb.GatesService.FromBucket:input_type -> gatespb.FromBucketRequest
	4, // 4: gatespb.GatesService.Transcode:input_type -> gatespb.TranscodeRequest
	1, // 5: gatespb.GatesService.Files:output_type -> gatespb.FilesResponse
	3, // 6: gatespb.GatesService.FromBucket:output_type -> gatespb.FromBucketResponse
	5, // 7: gatespb.GatesService.Transcode:output_type -> gatespb.TranscodeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gatespb_api_proto_init() }
func file_gatespb_api_proto_init() {
	if File_gatespb_api_proto != nil {
		return
	}
	file_gatespb_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gatespb_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FromBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gatespb_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gatespb_api_proto_goTypes,
		DependencyIndexes: file_gatespb_api_proto_depIdxs,
		MessageInfos:      file_gatespb_api_proto_msgTypes,
	}.Build()
	File_gatespb_api_proto = out.File
	file_gatespb_api_proto_rawDesc = nil
	file_gatespb_api_proto_goTypes = nil
	file_gatespb_api_proto_depIdxs = nil
}
