// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: gatespb/messages.proto

package gatespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Video      int32   `protobuf:"varint,1,opt,name=video,proto3" json:"video,omitempty"`
	Audio      int32   `protobuf:"varint,2,opt,name=audio,proto3" json:"audio,omitempty"`
	VideoCodec string  `protobuf:"bytes,3,opt,name=videoCodec,proto3" json:"videoCodec,omitempty"`
	VudioCodec string  `protobuf:"bytes,4,opt,name=vudioCodec,proto3" json:"vudioCodec,omitempty"`
	Channels   int32   `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	Time       float32 `protobuf:"fixed32,6,opt,name=time,proto3" json:"time,omitempty"`
	Width      int32   `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height     int32   `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Rate       string  `protobuf:"bytes,9,opt,name=rate,proto3" json:"rate,omitempty"`
	Pixfmt     string  `protobuf:"bytes,10,opt,name=pixfmt,proto3" json:"pixfmt,omitempty"`
	Data       int64   `protobuf:"varint,11,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MediaMetaData) Reset() {
	*x = MediaMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetaData) ProtoMessage() {}

func (x *MediaMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetaData.ProtoReflect.Descriptor instead.
func (*MediaMetaData) Descriptor() ([]byte, []int) {
	return file_gatespb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MediaMetaData) GetVideo() int32 {
	if x != nil {
		return x.Video
	}
	return 0
}

func (x *MediaMetaData) GetAudio() int32 {
	if x != nil {
		return x.Audio
	}
	return 0
}

func (x *MediaMetaData) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *MediaMetaData) GetVudioCodec() string {
	if x != nil {
		return x.VudioCodec
	}
	return ""
}

func (x *MediaMetaData) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *MediaMetaData) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MediaMetaData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaMetaData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaMetaData) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *MediaMetaData) GetPixfmt() string {
	if x != nil {
		return x.Pixfmt
	}
	return ""
}

func (x *MediaMetaData) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type TranscodeFileMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaMetaData    *MediaMetaData `protobuf:"bytes,2,opt,name=media_meta_data,json=mediaMetaData,proto3" json:"media_meta_data,omitempty"`
	TranscodedFileId string         `protobuf:"bytes,3,opt,name=transcoded_file_id,json=transcodedFileId,proto3" json:"transcoded_file_id,omitempty"`
}

func (x *TranscodeFileMetaData) Reset() {
	*x = TranscodeFileMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeFileMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeFileMetaData) ProtoMessage() {}

func (x *TranscodeFileMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeFileMetaData.ProtoReflect.Descriptor instead.
func (*TranscodeFileMetaData) Descriptor() ([]byte, []int) {
	return file_gatespb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TranscodeFileMetaData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranscodeFileMetaData) GetMediaMetaData() *MediaMetaData {
	if x != nil {
		return x.MediaMetaData
	}
	return nil
}

func (x *TranscodeFileMetaData) GetTranscodedFileId() string {
	if x != nil {
		return x.TranscodedFileId
	}
	return ""
}

type FileProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FileProgress) Reset() {
	*x = FileProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProgress) ProtoMessage() {}

func (x *FileProgress) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProgress.ProtoReflect.Descriptor instead.
func (*FileProgress) Descriptor() ([]byte, []int) {
	return file_gatespb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *FileProgress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TranscodeBodyBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bucket      string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectName  string `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	CallbackUrl string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *TranscodeBodyBucket) Reset() {
	*x = TranscodeBodyBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeBodyBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeBodyBucket) ProtoMessage() {}

func (x *TranscodeBodyBucket) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeBodyBucket.ProtoReflect.Descriptor instead.
func (*TranscodeBodyBucket) Descriptor() ([]byte, []int) {
	return file_gatespb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TranscodeBodyBucket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranscodeBodyBucket) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TranscodeBodyBucket) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *TranscodeBodyBucket) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type TranscodeBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url         string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	CallbackUrl string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *TranscodeBody) Reset() {
	*x = TranscodeBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gatespb_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscodeBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeBody) ProtoMessage() {}

func (x *TranscodeBody) ProtoReflect() protoreflect.Message {
	mi := &file_gatespb_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeBody.ProtoReflect.Descriptor instead.
func (*TranscodeBody) Descriptor() ([]byte, []int) {
	return file_gatespb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TranscodeBody) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranscodeBody) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TranscodeBody) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

var File_gatespb_messages_proto protoreflect.FileDescriptor

var file_gatespb_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70,
	0x62, 0x22, 0x99, 0x02, 0x0a, 0x0d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12,
	0x1e, 0x0a, 0x0a, 0x76, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x78, 0x66, 0x6d, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x69, 0x78, 0x66, 0x6d, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x95, 0x01,
	0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x22, 0x54, 0x0a, 0x0d, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x42,
	0x78, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x42, 0x0d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x1e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x73, 0x2f,
	0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0xa2,
	0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0xca,
	0x02, 0x07, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0xe2, 0x02, 0x13, 0x47, 0x61, 0x74, 0x65,
	0x73, 0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x07, 0x47, 0x61, 0x74, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gatespb_messages_proto_rawDescOnce sync.Once
	file_gatespb_messages_proto_rawDescData = file_gatespb_messages_proto_rawDesc
)

func file_gatespb_messages_proto_rawDescGZIP() []byte {
	file_gatespb_messages_proto_rawDescOnce.Do(func() {
		file_gatespb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_gatespb_messages_proto_rawDescData)
	})
	return file_gatespb_messages_proto_rawDescData
}

var file_gatespb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gatespb_messages_proto_goTypes = []interface{}{
	(*MediaMetaData)(nil),         // 0: gatespb.MediaMetaData
	(*TranscodeFileMetaData)(nil), // 1: gatespb.TranscodeFileMetaData
	(*FileProgress)(nil),          // 2: gatespb.FileProgress
	(*TranscodeBodyBucket)(nil),   // 3: gatespb.TranscodeBodyBucket
	(*TranscodeBody)(nil),         // 4: gatespb.TranscodeBody
}
var file_gatespb_messages_proto_depIdxs = []int32{
	0, // 0: gatespb.TranscodeFileMetaData.media_meta_data:type_name -> gatespb.MediaMetaData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gatespb_messages_proto_init() }
func file_gatespb_messages_proto_init() {
	if File_gatespb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gatespb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeFileMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeBodyBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gatespb_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscodeBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gatespb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gatespb_messages_proto_goTypes,
		DependencyIndexes: file_gatespb_messages_proto_depIdxs,
		MessageInfos:      file_gatespb_messages_proto_msgTypes,
	}.Build()
	File_gatespb_messages_proto = out.File
	file_gatespb_messages_proto_rawDesc = nil
	file_gatespb_messages_proto_goTypes = nil
	file_gatespb_messages_proto_depIdxs = nil
}
